server:
  port: 8081 # REST API (Tomcat)

spring:
  application:
    name: gold-api # Application name for logs and identification

grpc:
  server:
    port: 9090 # Port for gRPC server
    address: 0.0.0.0 # Bind gRPC server to all network interfaces (optional for local dev)

logging:
  level:
    net.devh.boot.grpc: DEBUG
    io.grpc: DEBUG
